global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'kafka-jmx'     # optional if you add JMX exporter on Kafka
    static_configs:
      - targets: ['nikunj_kafka_1:7071']

  - job_name: 'gin-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka-day4:8080']   # replace with your API service host:port in compose

  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka-day5_worker:9100']  # if you expose worker metrics
